### ISSUE TITLE
Maven import 

### ISSUE THREAD

**Issue by matteo5883** [contentful/rich-text-renderer.java#4]
Hi I followed the guide and I tryed to import the repo in my java project but I can't find com.contentfull.rich classes when I try to import them in my java class

**Comment by mariobodemann** [comment]
Hello,

In your path I can see a doubled `l` in `contentful`. Was this a typo here or in your configuration. If nothing helps, can you share more details, as in error messages, code you tried, etc.

Greetings,
Mario

**Comment by matteo5883** [comment]
Yes sorry just a typo error. In my pom.xml file I added 

```
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependency>
        <groupId>com.github.contentful</groupId>
        <artifactId>rich-text-renderer.java</artifactId>
        <version>master-25d243508f-1</version>
    </dependency>
    <dependency>
        <groupId>com.github.contentful</groupId>
        <artifactId>contentful.java</artifactId>
        <version>v10.3.1</version>
    </dependency>
```

but then I can't import HtmlContext and HtmlProcessor classes like if I don't import the repo in my project.

**Comment by mariobodemann** [comment]
Hey,

I just published an update on the versions, essentially a `jcenter()` was missing...

**Comment by matteo5883** [comment]
I can't still import in my project the repository

**Comment by vsthr** [comment]
Any updates on this? I am also not able to do an import...
